<a href="https://colab.research.google.com/github/sandeep838116/Numpy/blob/main/NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Computation on NumPy arrays : Universal functions

* Computation on NumPy array can be fast, or it can be very slow. The key to making it fast is to use vectorized operations, generally implemented through NumPy universal functions(ufuncs). ufuncs can be used to make repeated calculations on array elements much more efficient.

### The slowness of loops

* Python's default implementation(known as CPython) does some operations very slowly. This is in part due to the  dynamic, interpreted nature of the language : the fact that types are flexible,so that sequences of operations cannot be compiled down to efficient machine code as in the languages like c and fortran.
* The relative sluggishness of python generally manifests itself in situations where many small operation are being repeated-for instance, looping over arrays to operate on each element.

In [3]:
import numpy as np
np.random.seed(0)

def compute_reciprocal(values):
  output = np.empty(len(values))
  for i in range(len(values)):
    output[i]=1.0/values[i]
  return output

values=np.random.randint(1,10,size=5)
compute_reciprocal(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [4]:
big_array = np.random.randint(1,100, size=1000000)
%timeit compute_reciprocal(big_array)

5.24 s ± 769 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


It takes several seconds to compute these million operations and to store the result.Here is not only the operations themselves, but the type-checking and function dispatches that CPython must do at each cycle of the loop. If we were working in compiled code instead, this type specification would be known before the code executes and the result could be computed much more efficiently.

### UFuncs

*   For many types of operations, NumPy provides a convenient interface into just this kind of statically typed, compiled routine. This is known as vectorized operation.
*   You can acomplish this by simply performing an operation on the array, which will then be applied to each element.This vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution.



In [7]:
x = np.arange(5)

In [9]:
# Arithematic
print("x =",x)
print("x + 5 =",x+5)
print("x - 5 =",x-5)
print("x * 2 =",x*2)
print("x /2 =",x/2)
print("x // 2 =",x//2)
print("x ** 2 =",x**2)
print("-x =",-x)
print("x % 2 =",x%2)

x = [0 1 2 3 4]
x + 5 = [5 6 7 8 9]
x - 5 = [-5 -4 -3 -2 -1]
x * 2 = [0 2 4 6 8]
x /2 = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]
x ** 2 = [ 0  1  4  9 16]
-x = [ 0 -1 -2 -3 -4]
x % 2 = [0 1 0 1 0]


### NumPy Arithmetic Ufuncs Reference Table

| Operator | Ufunc | Description | Example (`a = [4, 5]`, `b = [2, 3]`) |
| :--- | :--- | :--- | :--- |
| **`+`** | `np.add` | Adds arguments, element-wise | `np.add(a, b)` $\rightarrow$ `[6, 8]` |
| **`-`** | `np.subtract` | Subtracts right argument from left argument | `np.subtract(a, b)` $\rightarrow$ `[2, 2]` |
| **`*`** | `np.multiply` | Multiplies arguments, element-wise | `np.multiply(a, b)` $\rightarrow$ `[8, 15]` |
| **`/`** | `np.divide` | Returns a true division of the inputs (floating-point results) | `np.divide(a, b)` $\rightarrow$ `[2.0, 1.66666667]` |
| **`//`** | `np.floor_divide` | Returns the largest integer smaller than or equal to the division | `np.floor_divide(a, b)` $\rightarrow$ `[2, 1]` |
| **`**`** | `np.power` | First array elements raised to powers from second array, element-wise | `np.power(a, b)` $\rightarrow$ `[16, 125]` |
| **`%`** | `np.remainder` | Returns the element-wise remainder of division | `np.remainder(a, b)` $\rightarrow$ `[0, 2]` |
| **`-`** *(unary)* | `np.negative` | Numerical negative, element-wise | `np.negative(a)` $\rightarrow$ `[-4, -5]` |
| **`+`** *(unary)* | `np.positive` | Numerical positive (leaves values unchanged) | `np.positive(a)` $\rightarrow$ `[4, 5]` |

In [10]:
x = np.array([1,-2,0,-4,-5])
np.absolute(x) #np.abs

array([1, 2, 0, 4, 5])

In [11]:
x=np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x) # np.abs or np.absolute can handle complex data, in which the absolute value returns the mgnitude.

array([5., 5., 2., 1.])

In [13]:
# Trignometric functions
theta = np.linspace(0,np.pi,3)

print("theta = ",theta)
print("sin(theta) = ",np.sin(theta))
print("cos(theta) = ",np.cos(theta))
print("tan(theta) = ",np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [15]:
#Inverse trignometry
x=[-1,0,1]

print("x = ",x)
print("arcsin(x) = ",np.arcsin(x))
print("arccos(x) = ",np.arccos(x))
print("arctan(x) = ",np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [ ]:
# Exponents and logarithms
