<a href="https://colab.research.google.com/github/sandeep838116/Numpy/blob/main/NumPy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Easy

In [1]:
# Import NumPy as np and print the version number.
import numpy as np
print(np.__version__)

2.1.3


In [2]:
# Create a 1D array of numbers from 0 to 9.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Create a 1D array of numbers from 1 to 10.
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Create a 3x3 NumPy array of all True's (boolean 1's).
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
# Create a 2x3 array filled entirely with zeros.
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# Create a 3x3 identity matrix.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Create a 1D array of 5 random floats between 0 and 1.
np.random.rand(15)

array([0.06655692, 0.2992734 , 0.15146193, 0.32711432, 0.46002042,
       0.6775974 , 0.54182154, 0.13941557, 0.23143382, 0.12149028,
       0.33457737, 0.20227187, 0.93689345, 0.61024363, 0.50962831])

In [14]:
# Create a 1D array of 10 evenly spaced numbers between 0 and 100.
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [15]:
# Convert a standard Python list [1, 2, 3] into a NumPy array.
np.array([1,2,3])

array([1, 2, 3])

In [16]:
# Create a 2x2 array filled with the exact number 7.
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
# Find the shape of arr = np.array([[1, 2], [3, 4]]).
arr = np.array([[1, 2], [3, 4]])
arr.shape

(2, 2)

In [19]:
# Find the number of dimensions of arr = np.array([[[1]]])
arr = np.array([[[1]]])
arr.ndim

3

In [20]:
# Find the total number of elements in arr = np.zeros((3, 4))
arr = np.zeros((3, 4))
arr.size

12

In [21]:
# Find the data type of arr = np.array([1.5, 2.5])
arr = np.array([1.5, 2.5])
arr.dtype

dtype('float64')

In [24]:
# Change the data type of arr = np.array([1.5, 2.5]) to integer.
arr = np.array([1.5, 2.5])
arr.astype(int)

array([1, 2])

In [25]:
# Extract all odd numbers from arr = np.arange(10)
arr = np.arange(10)
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [27]:
# Replace all odd numbers in arr = np.arange(10) with -1.
arr = np.arange(10)
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [29]:
# Get the first 5 elements of arr = np.arange(10)
arr = np.arange(10)
arr[:5]

array([0, 1, 2, 3, 4])

In [30]:
# Get the last 3 elements of arr = np.arange(10).
arr = np.arange(10)
arr[-3:]

array([7, 8, 9])

In [33]:
# Reverse a 1D array arr = np.arange(5)
arr = np.arange(5)
arr[::-1]

array([4, 3, 2, 1, 0])

In [35]:
# Extract the element in the 1st row and 2nd column of a 2D array.
arr = np.array([[1,2,3],[4,5,6]])
arr[0,1]

np.int64(2)

In [36]:
# Extract the entire first row of a 2D array.
arr[0,:]

array([1, 2, 3])

In [37]:
# Extract the entire last column of a 2D array.
arr[:,-1]

array([3, 6])

In [38]:
# Get the elements at index positions 1, 3, and 5 from arr = np.arange(10)
arr=np.arange(10)
i=[1,3,5]
arr[i]

array([1, 3, 5])

In [39]:
# Create a boolean mask for values strictly greater than 5 in arr = np.arange(10)
arr[arr>5]

array([6, 7, 8, 9])

In [40]:
# Reshape a 1D array of 9 elements into a 3x3 2D array.
arr = np.arange(0,9)
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
# Flatten a 2D array back into a 1D array.
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
# Transpose a 2x3 array arr into a 3x2 array.
arr=np.array([[1,2,3],[4,5,6]])
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
# Add a new axis to a 1D array arr to make it a column vector.
arr = np.arange(5)
arr[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [47]:
# Concatenate two 1D arrays a and b horizontally
a=np.arange(5)
b = np.arange(5)
np.hstack((a,b))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [48]:
# Stack two 1D arrays a and b vertically.
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [49]:
# Split an array of 10 elements into two equal arrays of 5.
arr = np.arange(10)
np.split(arr,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [50]:
# Add 5 to every element of arr = np.arange(10)
arr=arr+5
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
# Multiply every element of arr = np.arange(10) by 2.
arr*2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [52]:
# Add two arrays a and b of the same shape element-wise.
a+b

array([0, 2, 4, 6, 8])

In [53]:
# Multiply two arrays a and b element-wise
a*b

array([ 0,  1,  4,  9, 16])

In [54]:
# Compute the square of every element in an array.
arr**2

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196])

In [55]:
# Compute the square root of every element in an array.
np.sqrt(arr)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [56]:
# Compute the absolute value of arr = np.array([-1, -2, 3])
arr = np.array([-1, -2, 3])
np.abs(arr)

array([1, 2, 3])

In [57]:
# Perform the dot product of two arrays a and b.
np.dot(a,b)

np.int64(30)

In [58]:
# Find the mean of arr = np.array([1, 2, 3, 4, 5])
arr = np.array([1,2,3,4,5])
np.mean(arr)

np.float64(3.0)

In [59]:
# Find the median of arr = np.array([1, 2, 3, 4, 5]).
np.median(arr)

np.float64(3.0)

In [60]:
# Find the standard deviation of an array.
np.std(arr)

np.float64(1.4142135623730951)

In [61]:
# Find the minimum value in an array.
np.min(arr)

np.int64(1)

In [62]:
# Find the maximum value in an array.
np.max(arr)

np.int64(5)

In [63]:
# Find the index of the maximum value in an array.
np.argmax(arr)

np.int64(4)

In [64]:
# Find the index of the minimum value in an array.
np.argmin(arr)

np.int64(0)

In [65]:
# Compute the sum of all elements in a 2D array.
np.sum(arr)

np.int64(15)

In [66]:
# Sort a 1D array in ascending order
np.sort(arr)

array([1, 2, 3, 4, 5])

In [67]:
# Find the unique elements of an array arr = np.array([1,2,2,3,4,4,4,5,6,7,7,8]).
arr = np.array([1,2,2,3,4,4,4,5,6,7,7,8])
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# Intermediate

In [69]:
# Add a 1D array of shape (3,) to every row of a 2D array of shape (3, 3).
a = np.arange(3)
b = np.array([[1,3,2],[4,5,6]])
b+a

array([[1, 4, 4],
       [4, 6, 8]])

In [83]:
# Subtract a 1D array of shape (4,) from every column of a 2D array of shape (4, 4)
a = np.arange(4)

b = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])

result = b - a[:, np.newaxis]

print(result)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]]


In [72]:
# Multiply a 3x1 column vector by a 1x4 row vector to create a 3x4 matrix using broadcasting.
a = np.array([[1],[2],[3]])
b = np.array([[1,2,3,4]])
a*b

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [80]:
# Normalize the columns of a 2D array (subtract the column mean and divide by the column standard deviation).
arr = np.array([[1],[2],[3],[4],[5]])
(arr - np.mean(arr, axis=0)) / np.std(arr, axis=0)

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [79]:
# Center the rows of a 2D array by subtracting the mean of each row from its respective row.
arr = np.array([[1,2,3,4,5,6,7,8,9],[5,6,7,8,9,4,3,2,1]])
arr - np.mean(arr, axis=1, keepdims=True)

array([[-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4., -1., -2., -3., -4.]])

In [84]:
# Extract all elements from a 2D array that are strictly greater than 5 and less than 15.
b = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])
b[(b>5)&(b<15)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
# Get the indices of the top 3 largest values in a 1D array.
arr = np.array([6,7,4,2,3,1,9,0])
np.argsort(arr)[-3:]

array([0, 1, 6])

In [89]:
# Replace all negative values in a 2D array with 0 without using any explicit loops.
b = np.array([[ 1,  -2,  3,  -4],
              [ 5,  6,  -7,  8],
              [ -9, 10, 11, -12],
              [-13, 14, -15, 16]])
b[b<0]=0
b

array([[ 1,  0,  3,  0],
       [ 5,  6,  0,  8],
       [ 0, 10, 11,  0],
       [ 0, 14,  0, 16]])

In [90]:
# Extract the main diagonal elements of a 4x4 matrix into a 1D array.
b = np.array([[ 1,  -2,  3,  -4],
              [ 5,  6,  -7,  8],
              [ -9, 10, 11, -12],
              [-13, 14, -15, 16]])
np.diag(arr)

array([[6, 0, 0, 0, 0, 0, 0, 0],
       [0, 7, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 9, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [92]:
# Swap the first and second rows of a 3x3 array in a single line.
c = np.array([[ 1,  -2,  3],
              [ 5,  6,  -7],
              [ -9, 10, 11]])
c[[1,0,2],:]

array([[ 5,  6, -7],
       [ 1, -2,  3],
       [-9, 10, 11]])

In [98]:
# Reverse the order of the columns in a 2D array.
c[:,::-1]

array([[ 3, -2,  1],
       [-7,  6,  5],
       [11, 10, -9]])

In [100]:
# Use boolean indexing to extract only the rows of a 2D array where the value in the first column is greater than 2.
c[c[:,0]>2]

array([[ 5,  6, -7]])

In [104]:
# Create a new array that has the string 'Pos' where an existing array arr is > 0, and 'Neg' where it is <= 0.
arr = np.array([10, -5, 0, 3, -2, 7])
new_arr = np.where(arr > 0, 'Pos', 'Neg')
new_arr

array(['Pos', 'Neg', 'Neg', 'Pos', 'Neg', 'Pos'], dtype='<U3')

In [107]:
# Generate a 3x3 array of random integers drawn from a discrete uniform distribution between 10 and 50 (exclusive).
uniform_arr = np.random.randint(10,50,size=(3,3))
uniform_arr

array([[19, 12, 31],
       [24, 43, 23],
       [17, 26, 29]])

In [110]:
# Create a 1000-element 1D array drawn from a normal distribution with a mean of 5 and a standard deviation of 2.
normal_arr = np.random.normal(5,2,size=1000)
normal_arr

array([ 4.95750149,  5.3382129 ,  1.35559789,  5.09098893,  6.07357013,
        5.10008714,  5.75591887,  4.64477039,  3.75634677,  5.12359081,
        4.75135916,  4.61982696,  7.07294196,  4.60722553,  3.5921799 ,
        3.38224665,  5.57863374, -0.04649937,  3.29407061,  8.3290819 ,
        7.20059737,  5.73637777,  7.41563539,  4.58183342,  3.60786099,
        4.63493046,  7.33463285,  5.08931437,  4.44101815,  7.9115492 ,
        5.90921826,  8.3418985 ,  1.22595047,  5.44376728,  6.56164562,
        7.9703839 ,  6.2889919 ,  4.51235935,  3.32963526,  3.65344274,
        4.8853911 ,  9.89071185,  0.78640607,  4.37603594,  7.88062147,
        2.10923834,  4.51569889, -0.23894799, 10.45425758,  4.56583499,
        9.68095542,  4.54646815,  4.56287268,  4.67314755,  8.40875562,
        2.64759745,  7.31477152,  5.61067537,  4.48046017,  4.26896996,
        8.28782853,  4.81283605,  5.83300801,  6.91493944,  4.31196952,
        6.35623862,  4.25847677,  3.45995074,  1.38409442,  4.26

In [114]:
# Randomly shuffle the rows of a 2D array without altering the order of elements within each row.
np.random.shuffle(uniform_arr)
uniform_arr

array([[17, 26, 29],
       [24, 43, 23],
       [19, 12, 31]])

In [115]:
# Draw 5 random samples (without replacement) from a 1D array of 20 elements.
np.random.choice(arr,size=5,replace=False)

array([-5,  7,  3,  0, -2])

In [118]:
# Generate a random 4x4 symmetric matrix.
a = np.random.rand(4,4)
a = a + a.T
a

array([[1.77421475, 0.93988342, 0.78986264, 0.9992414 ],
       [0.93988342, 1.26342041, 1.15887991, 0.8913814 ],
       [0.78986264, 1.15887991, 1.16953549, 0.93408376],
       [0.9992414 , 0.8913814 , 0.93408376, 0.54958678]])