<a href="https://colab.research.google.com/github/sandeep838116/Numpy/blob/main/NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Computation on NumPy arrays : Universal functions

* Computation on NumPy array can be fast, or it can be very slow. The key to making it fast is to use vectorized operations, generally implemented through NumPy universal functions(ufuncs). ufuncs can be used to make repeated calculations on array elements much more efficient.

### The slowness of loops

* Python's default implementation(known as CPython) does some operations very slowly. This is in part due to the  dynamic, interpreted nature of the language : the fact that types are flexible,so that sequences of operations cannot be compiled down to efficient machine code as in the languages like c and fortran.
* The relative sluggishness of python generally manifests itself in situations where many small operation are being repeated-for instance, looping over arrays to operate on each element.

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocal(values):
  output = np.empty(len(values))
  for i in range(len(values)):
    output[i]=1.0/values[i]
  return output

values=np.random.randint(1,10,size=5)
compute_reciprocal(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array = np.random.randint(1,100, size=1000000)
%timeit compute_reciprocal(big_array)

2.56 s ± 792 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


It takes several seconds to compute these million operations and to store the result.Here is not only the operations themselves, but the type-checking and function dispatches that CPython must do at each cycle of the loop. If we were working in compiled code instead, this type specification would be known before the code executes and the result could be computed much more efficiently.

### UFuncs

*   For many types of operations, NumPy provides a convenient interface into just this kind of statically typed, compiled routine. This is known as vectorized operation.
*   You can acomplish this by simply performing an operation on the array, which will then be applied to each element.This vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution.



In [3]:
x = np.arange(5)

In [4]:
# Arithematic
print("x =",x)
print("x + 5 =",x+5)
print("x - 5 =",x-5)
print("x * 2 =",x*2)
print("x /2 =",x/2)
print("x // 2 =",x//2)
print("x ** 2 =",x**2)
print("-x =",-x)
print("x % 2 =",x%2)

x = [0 1 2 3 4]
x + 5 = [5 6 7 8 9]
x - 5 = [-5 -4 -3 -2 -1]
x * 2 = [0 2 4 6 8]
x /2 = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]
x ** 2 = [ 0  1  4  9 16]
-x = [ 0 -1 -2 -3 -4]
x % 2 = [0 1 0 1 0]


### NumPy Arithmetic Ufuncs Reference Table

| Operator | Ufunc | Description | Example (`a = [4, 5]`, `b = [2, 3]`) |
| :--- | :--- | :--- | :--- |
| **`+`** | `np.add` | Adds arguments, element-wise | `np.add(a, b)` $\rightarrow$ `[6, 8]` |
| **`-`** | `np.subtract` | Subtracts right argument from left argument | `np.subtract(a, b)` $\rightarrow$ `[2, 2]` |
| **`*`** | `np.multiply` | Multiplies arguments, element-wise | `np.multiply(a, b)` $\rightarrow$ `[8, 15]` |
| **`/`** | `np.divide` | Returns a true division of the inputs (floating-point results) | `np.divide(a, b)` $\rightarrow$ `[2.0, 1.66666667]` |
| **`//`** | `np.floor_divide` | Returns the largest integer smaller than or equal to the division | `np.floor_divide(a, b)` $\rightarrow$ `[2, 1]` |
| **`**`** | `np.power` | First array elements raised to powers from second array, element-wise | `np.power(a, b)` $\rightarrow$ `[16, 125]` |
| **`%`** | `np.remainder` | Returns the element-wise remainder of division | `np.remainder(a, b)` $\rightarrow$ `[0, 2]` |
| **`-`** *(unary)* | `np.negative` | Numerical negative, element-wise | `np.negative(a)` $\rightarrow$ `[-4, -5]` |
| **`+`** *(unary)* | `np.positive` | Numerical positive (leaves values unchanged) | `np.positive(a)` $\rightarrow$ `[4, 5]` |

In [5]:
x = np.array([1,-2,0,-4,-5])
np.absolute(x) #np.abs

array([1, 2, 0, 4, 5])

In [6]:
x=np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x) # np.abs or np.absolute can handle complex data, in which the absolute value returns the mgnitude.

array([5., 5., 2., 1.])

In [7]:
# Trignometric functions
theta = np.linspace(0,np.pi,3)

print("theta = ",theta)
print("sin(theta) = ",np.sin(theta))
print("cos(theta) = ",np.cos(theta))
print("tan(theta) = ",np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [8]:
#Inverse trignometry
x=[-1,0,1]

print("x = ",x)
print("arcsin(x) = ",np.arcsin(x))
print("arccos(x) = ",np.arccos(x))
print("arctan(x) = ",np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [9]:
# Exponents and logarithms
x=[1,2,3]
print("x = ",x)
print("e^x = ",np.exp(x))
print("2^x = ",np.exp2(x))
print("3^x = ",np.power(3,x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [10]:
# The inverse of exponents are logarithms.
# The basic np.log gives the natural logarithm : if you prefer to compute the base-2 logarithm or the base-10 logarithm , these are available.
x=[1,2,4,10]
print('x = ',x)
print('ln(x) = ',np.log(x))
print('log2(x) = ',np.log2(x))
print('log10(x) = ',np.log10(x))

x =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.38629436 2.30258509]
log2(x) =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [11]:
# There are also some specialized versions that are useful for maintaining precision with very small input.
# When x is very small, these functions give more precise values than if the raw np.log or np.exp were used.
x =[0,0.001,0.01,0.1]
print('exp(x)- 1 = ',np.expm1(x))
print('log(1+x) = ',np.log1p(x))

exp(x)- 1 =  [0.         0.0010005  0.01005017 0.10517092]
log(1+x) =  [0.         0.0009995  0.00995033 0.09531018]


## Advanced Ufunc Features

#### Specifying output

In [12]:
# For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary
# array, you can use to write computation results directly to the memory location where you'd like to them to be. For all ufuncs, you can do this using out argument
# of the function :
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [13]:
# This can even be used with array views. For example, we can write the results of a computation to every other element of a specified array:
y=np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

# Note:- if we had written y[::2]=2**x, this would have resulted in the creation of a temporary array to hold the results of 2**x, followed by a second operation
# copying those values into the y array.

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


### Aggregates

In [16]:
# For binary ufuncs, there are some intresting aggregates that can be computed directly from the object.
# For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc.
# A reduce repeatedly applies a given operation to the element of an array until only a single result remains.
x = np.arange(1,20)
print(np.add.reduce(x))

190


In [17]:
print(np.add.accumulate(x))    # If we'd like to store the intermediate results of the computation, we can instead use accumulate.

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190]


### Other products

In [18]:
# Any ufunc can compute the output of all pairs of two different inputs using the outer method. This allows you, in one line, to do things like create a multiplication table.
x=np.arange(1,7)
print(np.multiply.outer(x,x))

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


## Aggregations: Min, Max, and Everything In Between

- Often when you faced a large amount of data, a first step is to compute summary statistics of the data. NumPy has fast built-in aggregation functions for working on arrays.

#### Summing the values in an array

In [21]:
L=np.random.random(100)
print(sum(L))   # Python's built-in sum

46.63620765216888


In [24]:
# The syntax is quite similar to that of NumPy's sum function, and the result is the same in the simplest case. However, because it executes the operation in
# compiled code, NumPy's version of the operation is computed much more quickly.
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

121 ms ± 36.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
375 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# Be careful, though: the sum function and the np.sum function are not identical, which can sometimes lead to confusion! In particular,
# their optional arguments have different meanings, and np.sum is aware of multiple array dimensions.

#### Minimum and maximum
- Similarly, Python has built-in min and max functions, used to find the minimum value and maximum value of any given array.
- NumPy's corresponding functions have similar syntax, and again operate much more quickly.


In [25]:
min(big_array), max(big_array)  #Python's built-in function

(np.float64(2.067514368597756e-07), np.float64(0.999997425247757))

In [26]:
np.min(big_array), np.max(big_array)

(np.float64(2.067514368597756e-07), np.float64(0.999997425247757))

#### Multidimensional aggregates

In [27]:
# By default, each NumPy aggregation function will return will return the aggregates over the entire array.
# Note :- One common type of aggregation operation is an aggregates along a row or column. Say you have some data stored in a two-dimensional array.
# Aggregation functions take an additional argument specifying the axis along which the aggregate is computed.
M= np.random.random((3,4))
print(M.min(axis=0))  #column
print(M.min(axis=1))  #row

[0.46211    0.22878899 0.03386599 0.17496768]
[0.03386599 0.30277679 0.22878899]


- The axis keyword specifies the dimension of the array that will be collapsed, rather than the dimension that will returned. So specifying axis=0, means that the first axis will be collapsed : for two-dimensional array, this means that the values within each column will be aggregated.

#### Other aggregation functions

In [ ]:
# NumPy provides many other aggregation functions, additionally most aggregates have NaN-safe counter part that computes the result while ignoring missing values,
# which are marked by the special IEEE floating-point NaN value.

| Function Name | NaN-safe Version | Description |
| :--- | :--- | :--- |
| `np.sum` | `np.nansum` | Computes the sum of all elements. |
| `np.prod` | `np.nanprod` | Computes the product of all elements. |
| `np.mean` | `np.nanmean` | Computes the arithmetic mean (average). |
| `np.std` | `np.nanstd` | Computes the standard deviation. |
| `np.var` | `np.nanvar` | Computes the variance. |
| `np.min` | `np.nanmin` | Finds the minimum value. |
| `np.max` | `np.nanmax` | Finds the maximum value. |
| `np.argmin` | `np.nanargmin` | Returns the index of the minimum value. |
| `np.argmax` | `np.nanargmax` | Returns the index of the maximum value. |
| `np.median` | `np.nanmedian` | Computes the median (middle value). |
| `np.percentile` | `np.nanpercentile` | Computes the *q*-th percentile of the data. |
| `np.any` | *N/A* | Evaluates whether any elements evaluate to `True`. |
| `np.all` | *N/A* | Evaluates whether all elements evaluate to `True`. |



- Note: Functions like np.any and np.all do not have distinct NaN-safe versions because NaN is evaluated as truthy in standard Python boolean contexts. If you need to explicitly ignore NaN values for boolean evaluations, you typically mask them out first using np.isnan().