<a href="https://colab.research.google.com/github/sandeep838116/Numpy/blob/main/NumPy_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sorting Arrays
- Up to this point we have been concerned mainly with tools to access and operate on array data with NumPy. This section covers algorithms related to sorting values in NumPy arrays.

In [2]:
# Selection sort
import numpy as np

def selection_sort(x):
  for i in range(len(x)):
    swap=i+np.argmin(x[i:])
    (x[i],x[swap])=(x[swap],x[i])
  return x

x=np.array([8,6,9,7,2,4])
selection_sort(x)

array([2, 4, 6, 7, 8, 9])

## Fast Sorting in NumPy: np.sort and np.argsort
- Although Python has built-in sort and sorted functions to work with with list, we won't discuss them here because NumPy's np.sort function turns out to be much more efficient and useful for our purpose.
- By default np.sort uses O[N log N] ,quick sort-algorithm, though mergesort and heapsort are also available.

In [3]:
# To return a sorted version of the array without modifying the input, you can use np.sort:
x=np.array([2,8,4,9,1,3,7,0])
np.sort(x)

array([0, 1, 2, 3, 4, 7, 8, 9])

In [4]:
# If you prefere to sort the array in-place, you can instead use the sort method of arrays:
x.sort()
print(x)

[0 1 2 3 4 7 8 9]


In [5]:
# A related function is argsort, which instead returns the indices of the sorted elements:
x=np.array([2,8,4,9,1,3,7,0])
i = np.argsort(x)
print(i)

[7 4 0 5 2 6 1 3]


In [6]:
x[i]

array([0, 1, 2, 3, 4, 7, 8, 9])

### Sorting along rows and columns
- A useful feature of NumPy's sorting algorithm is the ability to sort along specific rows and columns of multidimensional array using the axis argument.

In [8]:
rand = np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [9]:
#sort each column of x
np.sort(x,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [10]:
#sort each row of x
np.sort(x,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

Keep in mind that this treats each row or column as an independent array, and any relationship between the row and column values will be lost!

## Partial Sorts: Partitioning
- Sometimes we are not intrested in sorting the entire array, but simply want to find the K smallest values in the array. NumPy provides this in the **np.partition** function.
- np.partition takes an array and a number K; the result is a new array with the smalles K values to the left of the partition, and the remaining values to the right, in arbitrary order.

In [14]:
x=np.array([7,2,3,1,6,5,4,7,5,25,71,12,23,21,36,45,64])
np.partition(x,4)

array([ 1,  2,  3,  4,  5,  5,  6,  7,  7, 12, 21, 23, 25, 36, 45, 64, 71])

Note that the first three values in the resulting array are the three smallest in the array, and the remaining array positions contain the remaining values.

In [12]:
x=np.array([7,2,3,1,6,5,4])
np.partition(x,3)

array([1, 2, 3, 4, 5, 6, 7])

Why did it fully sort the array?
np.partition does not force the left and right sides to be scrambled; it just doesn't waste computational power guaranteeing they are sorted. However, for very small arrays like yours (only 7 elements), the underlying partitioning algorithm (introselect) often **ends up fully sorting the elements just by chance while shifting things around to find the pivot.**

In [16]:
#Similarly to sorting, we can partition along an arbitrary axis of multidimensional array:
rand = np.random.RandomState(42)
y=rand.randint(0,10,(4,6))
print(y)
np.partition(y,2,axis=1)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

Just as there is np.argsort that computes indices of the sort, there is a np.argpartition that computes indices of the partition.

# Structure Data: NumPy's Structured Arrays

while often our data can be well represented by a homogenous array of values, sometimes this is not the case. This section demonstrates the use of NumPy's structured array and record arrays, which provides efficient storage for compound, heterogenous data. While the patterns shown here are useful for simple operations, scenarios like this often lend themselves to the use of Pandas Dataframe.

In [17]:
name =["Alice","Bob","Cathy","Doug"]
age=[25,45,37,19]
wieght = [55.0,85.5,68.0,61.5]

There's nothing here that tells us that the three arrays are related; it would be more natural if we could use a single structure to  store all of this data. NumPy can handle this through structured arrays, which are arrays with coumpound data types.

In [19]:
# Use a compound data type for structured arrays
data = np.zeros(4,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


1.   U10 -> unicode string of maximum length 10
2.   i4 -> 4-byte integer
3.   f8 -> 8-byte float



In [20]:
# Now that we have created an empty container array, we can fill the array with our list of values:
data['name']=name
data['age']=age
data['weight']=wieght
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [21]:
#Access data
data['age']

array([25, 45, 37, 19], dtype=int32)

In [22]:
data[0]

np.void(('Alice', 25, 55.0), dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [23]:
# Boolean masking
# Get names where age <30
data[data['age']<30]['name']

array(['Alice', 'Doug'], dtype='<U10')

## Creating Structured array


In [25]:
#  Structured array can be specified in a number of ways. Earlier we saw the dictionary method.
np.dtype({'names':('name','age','weight'),'formats':('U10','i4','f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [26]:
# For clarity, numerical types can be specified with Python type or NumPy dtypes instead:
np.dtype({'names':('name','age','weight'),'formats':((np.str_,10),int,np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [27]:
# A compound type can also be specified as a list of tuples:
np.dtype([('name','S10'),('age','i4'),('weight','f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [28]:
# If the names of the types do not matter to you, you can specify the types alone in a comma-separated string:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

| Character | Description | Example (Data Type) |
| :---: | :--- | :--- |
| **`?`** | Boolean (True or False) | `'?'` (boolean) |
| **`b`** | Byte (signed integer: -128 to 127) | `'b'` (int8) |
| **`B`** | Unsigned byte (0 to 255) | `'B'` (uint8) |
| **`i`** | Signed integer | `'i4'` (32-bit integer) |
| **`u`** | Unsigned integer | `'u8'` (64-bit unsigned integer) |
| **`f`** | Floating-point | `'f8'` (64-bit float) |
| **`c`** | Complex-floating point | `'c16'` (128-bit complex) |
| **`m`** | Timedelta (time differences) | `'m8[D]'` (timedelta in days) |
| **`M`** | Datetime (specific dates/times) | `'M8[Y]'` (datetime in years) |
| **`O`** | Python Object (e.g., list, dict) | `'O'` (Python object) |
| **`S`** / **`a`** | Byte-string (zero-terminated bytes) | `'S10'` (10-character byte string) |
| **`U`** | Unicode string | `'U20'` (20-character unicode string) |
| **`V`** | Raw data (Void) | `'V'` (used for arbitrary data chunks) |

## Record Arrays : Structured Arrays With a Twist
- NumPy also provides the **np.recarray** class, which is almost identical to the structured arrays just described, but with one additional feature: fields can be accessed as attributes rather than as dictionary keys.

In [29]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [30]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

The downside is that for record arrays, there is some extra overhead involved in accessing the fields, even when using the same syntax.