<a href="https://colab.research.google.com/github/sandeep838116/Numpy/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Importing numpy
import numpy as np
np.__version__

'2.0.2'

## Creating arrays from python list




*   Remember that unlike python lists, Numpy is constrained to arrays that contain the same data type.If types do not match Numpy will upcast if possible.
*   Unlike python list, Numpy arrays can be explicitly be multidimensional.



In [3]:
# Creating an array :- we can use np.array to create arrays from python list.
# 1D array
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# 3D array
c = np.array([
      [[1,2,3],[4,5,6]],
      [[7,8,9],[1,4,7]]
    ])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 4, 7]]])

In [6]:
# Shape of an array
# (columns,)
a.shape

(9,)

In [7]:
# (rows, columns)
b.shape

(2, 4)

In [8]:
# (layers, rows, columns)
# layers :-- How many 2D grids are stacked together
c.shape

(2, 2, 3)

In [9]:
# To visualize it perfectly, think of a 3D array like a book:

#   Layers (Axis 0): The number of pages in the book.

#   Rows (Axis 1): The lines of text on a single page.

#   Columns (Axis 2): The individual words in a single line.

# So, if you see an array with shape = (5, 4, 3), it literally means you have 5 separate 2D grids stacked together, and each of those grids has 4 rows and 3 columns.

In [10]:
# Dimension/rank/axes of array
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [11]:
# Size of an array
print(a.size)
print(b.size)
print(c.size)

9
8
12


In [12]:
# data type :- If we want to explicitly set the data type of the resulting array, we can use the dtype keyword.
d = np.array([85,5,2], dtype=float)
print(d)

[85.  5.  2.]


### Creating arrays from scratch

* For larger arrays,it is more efficient to create arrays from scratch using routines built into Numpy.

In [13]:
# Create an integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# create a 2D floating point array filled with 1s
np.ones((3,4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# create a 2D array filled with specific value (i.e, 3.14)
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
# create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# Note :- this is similar to the built-in range() function
np.arange(0,20,2)  #Note :- Here,20 is excluded

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# create an array of ten values evenly spaced between 0 and 1
np.linspace(0,1,10) # Note:- Here, 1 is included

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
# create 2D array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.65733149, 0.67475255, 0.45581619],
       [0.010228  , 0.25556663, 0.82457019],
       [0.45512076, 0.75098151, 0.55644838]])

In [19]:
# create 2D array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(4,4))

array([[-1.03220112, -1.32788023, -0.19871592, -1.95884472],
       [ 0.1980429 ,  0.66669154,  0.32626065, -0.46838343],
       [ 1.60780055, -0.83782643, -1.40084366, -1.69170556],
       [ 0.61280167,  0.73322551, -0.93785684, -0.24480869]])

In [20]:
# create 2D array of random integers in the interval[0,10)
np.random.randint(0,10,(3,3))

array([[0, 6, 4],
       [6, 2, 4],
       [2, 6, 4]])

In [21]:
# create a 2D identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# create an uninitialized array of three integers
# the values will be whatever happens to already exist at that memory location
np.empty(4)

array([1., 1., 1., 1.])

In [23]:
# Changing the shape of array
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

## The Basics of Numpy array
* Attribute of arrays :- Determining the shape, size, memory consumption and data type of arrays.
* Indexing of arrays :- Getting and setting the value of individual array elements.
* Slicing of arrays :- Getting and setting of smaller subarrays within a larger array.
* Reshaping of arrays :- Changing the shape of a given array.
* Joining and splitting of arrays :- Combining multiple arrays into one, and splitting one array into many.

### Numpy array attributes

In [24]:
np.random.seed(0)
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [25]:
print('x3 ndim : ',x3.ndim)
print('x3 shape : ',x3.shape)
print('x3 size : ',x3.size)

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60


In [26]:
print('x3 dtype : ',x3.dtype)
print('x3 itemsize : ',x3.itemsize,'bytes') #list the size of each array element in bytes
print('x3 nbytes : ',x3.nbytes,'bytes')   # list the total size of the array in bytes

x3 dtype :  int64
x3 itemsize :  8 bytes
x3 nbytes :  480 bytes


### Array indexing - Acessing single element

In [27]:
# In 1D array, you can access the ith value(counting from zero) by specifying the desired index in square brackets, just as python list.
# To index from the end of the array, you can use negative indices
print(x1[0])

5


In [28]:
print(x1[5])

9


In [29]:
print(x1[-1])

9


In [30]:
# In multidimensional array, you can access items using a comma-separated tuple of indices.

print(x2[0,0])

3


In [31]:
print(x2[2,-1])

7


In [32]:
# you can also modify values using any of the above index notation.
x2[0,0]=15

In [33]:
print(x2)

[[15  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
#Note:- Unlike python list, Numpy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array,
#the value will be silently truncated.
x1[0]=3.14 # this value will not be assigned.
x1

array([3, 0, 3, 3, 7, 9])

### Array slicing - accessing subarrays

Just as we can use square brackets to access individual array elements, we can use them to acess subarrays with the slice notation, marked by the colon(:) character.
The Numpy slicing syntax follows that of the standard python list, to access a slice of an array x, use this :  **x[start:stop:step]** .
If any of these are unspecified, they default to the values start =0 , stop=size of the dimension, step =1

In [36]:
# one dimensional

x= np.arange(10)

In [37]:
x[:5] #First 5 elements

array([0, 1, 2, 3, 4])

In [38]:
x[5:] #elements after index 5

array([5, 6, 7, 8, 9])

In [39]:
x[3:8] # element after index 3 and till index 8

array([3, 4, 5, 6, 7])

In [40]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [42]:
x[1::2] # every other element from index 1

array([1, 3, 5, 7, 9])

In [43]:
# A potential confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped.
x[::-1] # all element reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [46]:
# Multidimensional subarrays
# Multidimensional slices work in the same way, with multiple slices separated by comas.
x2

array([[15,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [49]:
x2[:2,:3] # two rows and three columns

array([[15,  5,  2],
       [ 7,  6,  8]])

In [51]:
x2[:,::2] #all rows, every other column

array([[15,  2],
       [ 7,  8],
       [ 1,  7]])

In [52]:
x2[::-1,::-1] #reversed

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 15]])

In [55]:
# One commonly needed routine is accessing single rows or columns of an array. You can do this by combining indexing and slicing , using an empty slice marked by single colon(:)
print(x2[:,0]) # first column of x2
print(x2[0,:])  #first row of x2
print(x2[0])    # equivalent to x2[0,:]

[15  7  1]
[15  5  2  4]
[15  5  2  4]


#### Subarrays as no-copy view

One important-and extremely useful-thing to know about array slices is that they return view rather than copies of the array data. This is one area in which Numpy arry slicing differs from python list slicing: in lists, slices will be copies.

In [56]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[15  5]
 [ 7  6]]


In [57]:
x2_sub[0,0]=99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [58]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behaviour is actually quite useful : it means that when we work with large datasets, we can access and process pieces of these dataset without the need to copy the underlying data buffer.

In [59]:
# Creating copies of the arrays.
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [61]:
x2_sub_copy[0,0]=50
print(x2_sub_copy)

[[50  5]
 [ 7  6]]


In [62]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of arrays

In [63]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* Note that for this to work, the size of the intial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the intial array, but no contiguous memory buffers this is not always th case.
* Another common reshaping pattern is the conversion of a one-dimensional array into two-dimensional row or column matrix. You can do this with reshape method, or more easily by making use of the newaxis keyword within a slice operation.

In [64]:
x=np.array([1,2,3])
x.reshape((1,3)) #row vector via reshape

array([[1, 2, 3]])

In [65]:
x[np.newaxis,:] #row vector via newaxis

array([[1, 2, 3]])

In [66]:
x.reshape((3,1))  # column vector via reshape

array([[1],
       [2],
       [3]])

In [67]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

### Array concatenation and splittng

In [68]:
# Concatenation or joining of two arrays in Numpy, is primarly accomplished through the routines.
# np.concatenate,np.hstack, np.vstack takes a tuple or list of arrays as its first argument.
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [69]:
#You can also concatenate more than two arrays at once.
z=np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# np.concatenate can also be used for two-dimensional array
grid =np.array([[1,2,3],[4,5,6]])

In [71]:
np.concatenate([grid,grid]) #concatenate along first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [72]:
np.concatenate([grid,grid],axis=1) # concatenate along second axis(zero-indexed)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [73]:
# Vertically stack the array
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
# Horizontally stack the array
y = np.array([[50],[50]])
np.hstack([y,grid])

array([[50,  1,  2,  3],
       [50,  4,  5,  6]])

#### Splitting of arrays

In [ ]:
# Spliting is implemented by the functions np.split, np.hsplit, np.vsplit. For each of these, we can pass a list of indices giving the split points.

In [78]:
x=[1,2,3,4,5,6,7,8,9]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8 9]


In [79]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [82]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
