<a href="https://colab.research.google.com/github/sandeep838116/Numpy/blob/main/NumPy_exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Import NumPy and Check the Version

**Question:** Import numpy as np and print the version number.

**Expected Output:**

```text
2.0.2
```


In [1]:
import numpy as np
print(np.__version__)

2.1.3


## 2. Create a 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.

**Expected Output:**

```text
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```


In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Create a Boolean Array

**Question:** Create a 3×3 numpy array of all True values.

**Expected Output:**

```text
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
```


In [3]:
arr1 = np.full((3,3),True)
arr1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. Extract Items That Satisfy a Condition

**Question:** Extract all odd numbers from arr.

**Expected Output:**

```text
array([1, 3, 5, 7, 9])
```


In [4]:
arr[1::2]

array([1, 3, 5, 7, 9])

## 5. Replace Items That Satisfy a Condition

**Question:** Replace all odd numbers in arr with -1.

**Expected Output:**

```text
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```


In [5]:
arr[1::2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. Replace Items Without Affecting the Original Array

**Question:** Replace all odd numbers in arr with -1 without modifying the original arr.

**Expected Output:**

```text
out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr: [0 1 2 3 4 5 6 7 8 9]
```


In [6]:
arr=np.arange(10)

#Method 1:--
# out = np.copy(arr)
# out[out%2!=0]=-1
# out

#method 2:--
out = np.where(arr % 2 != 0, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 7. Reshape an Array

**Question:** Convert the 1D array arr to a 2D array with 2 rows.

**Expected Output:**

```text
[[0 1 2 3 4]
 [5 6 7 8 9]]
```


In [7]:
arr=arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. Stack Two Arrays Vertically

**Question:** Stack arrays a and b vertically.

**Expected Output:**

```text
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```


In [8]:
arr1 = np.ones((2,5),dtype=int)
np.vstack((arr,arr1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. Stack Two Arrays Horizontally

**Question:** Stack arrays a and b horizontally.

**Expected Output:**

```text
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
```


In [9]:
np.hstack((arr,arr1))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10. Generate Custom Sequences Without Hardcoding

**Question:** Using only numpy functions and the input array a, produce an array that first repeats each element 3 times, then tiles the whole array 3 times.

**Expected Output:**

```text
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```


In [10]:
num=np.array([1,2,3])
# np.r_ is a unique, shorthand tool in NumPy used primarily for row-wise concatenation and quickly building arrays.
result = np.r_[np.repeat(num, 3), np.tile(num, 3)]
result

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. Get Common Items Between Two Arrays

**Question:** Find the common items between arrays a and b.

**Expected Output:**

```text
[2 4]
```


In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


## 12. Remove Items Present in Another Array

**Question:** From array a, remove all items that are present in array b.

**Expected Output:**

```text
[1 2 3 4]
```


In [12]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

result = np.setdiff1d(a,b)
result

array([1, 2, 3, 4])

## 13. Find Positions Where Two Arrays Match

**Question:** Get the positions (indices) where elements of a and b are equal.

**Expected Output:**

```text
(array([1, 3, 5, 7]),)
```


In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c=np.where(a==b)
c

(array([1, 3, 5, 7]),)

## 14. Extract Numbers Within a Given Range

**Question:** From array a, extract all items between 5 and 10 (inclusive).

**Expected Output:**

```text
[ 6  9 10]
```


In [14]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

result = a[((a>=5) & (a<=10))]
result

array([ 6,  9, 10])

## 15. Vectorize a Scalar Function to Work on Arrays

**Question:** Convert the scalar function maxx into a vectorized version that works element-wise on arrays a and b.

**Expected Output:**

```text
[6. 7. 9. 8. 9. 7. 5.]
```


In [15]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])   #Returns an object that acts like pyfunc, but takes arrays as input.

result = pair_max(a,b)
result

array([6., 7., 9., 8., 9., 7., 5.])

## 16. Swap Two Columns in a 2D Array

**Question:** Swap columns 1 and 2 in the array arr.

**Expected Output:**

```text
[[1 0 2]
 [4 3 5]
 [7 6 8]]
```


In [16]:
arr = np.arange(9).reshape(3,3)
result = arr[:,[1,0,2]]
result

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. Swap Two Rows in a 2D Array

**Question:** Swap rows 1 and 2 in the array arr.

**Expected Output:**

```text
[[3 4 5]
 [0 1 2]
 [6 7 8]]
```


In [17]:
arr = np.arange(9).reshape(3,3)
result = arr[[1,0,2],:]
result

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## 18. Reverse the Rows of a 2D Array

**Question:** Reverse the row order of the 2D array arr.

**Expected Output:**

```text
[[6 7 8]
 [3 4 5]
 [0 1 2]]
```


In [18]:
arr = np.arange(9).reshape(3,3)
result = arr[::-1]
result


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 19. Reverse the Columns of a 2D Array

**Question:** Reverse the column order of the 2D array arr.

**Expected Output:**

```text
[[2 1 0]
 [5 4 3]
 [8 7 6]]
```


In [19]:
arr = np.arange(9).reshape(3,3)
result = arr[:,::-1]
result


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## 20. Create a 2D Array of Random Floats Between 5 and 10

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.

**Expected Output:**

```text
[[ 8.501  9.105  6.859]
 [ 9.763  9.877  7.135]
 [ 7.49   8.334  6.168]
 [ 7.75   9.945  5.274]
 [ 8.085  5.562  7.312]]
```


In [20]:
arr=np.random.uniform(5,10,(5,3))
arr

array([[6.76499511, 7.8342298 , 8.25996313],
       [8.32455047, 7.4058495 , 9.66398707],
       [6.20016489, 8.08248214, 6.80558274],
       [6.46337401, 9.88796102, 8.21118443],
       [9.05955621, 5.01443129, 7.82414194]])

## 21. Print Only 3 Decimal Places

**Question:** Set NumPy print options so that the array rand\_arr displays only 3 decimal places.

**Expected Output:**

```text
[[ 0.443  0.109  0.97 ]
 [ 0.388  0.447  0.191]
 [ 0.891  0.474  0.212]
 [ 0.609  0.518  0.403]]
```


In [21]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr[:4])

[[0.225 0.726 0.821]
 [0.561 0.393 0.954]
 [0.105 0.94  0.693]
 [0.406 0.967 0.697]]


## 22. Suppress Scientific Notation in Print Output

**Question:** Pretty print rand\_arr by suppressing scientific notation (like 1e10).

**Expected Output:**

```text
[[ 0.000543  0.000278  0.000425]
 [ 0.000845  0.000005  0.000122]
 [ 0.000671  0.000826  0.000137]]
```


In [22]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


## 23. Limit the Number of Printed Items

**Question:** Set NumPy print options so that array a displays a maximum of 6 elements, with the rest replaced by ellipsis.

**Expected Output:**

```text
[ 0  1  2 ... 12 13 14]
```


In [23]:
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


## 24. Print the Full Array Without Truncating

**Question:** Print the full numpy array a without truncation, even when the print threshold is set low.

**Expected Output:**

```text
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
```


In [24]:
import sys
np.set_printoptions(threshold=6)
a = np.arange(15)

np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## 25. Import a Dataset With Mixed Types

**Question:** Import the iris dataset from the URL, keeping the text (species) column intact alongside the numeric columns.

**Expected Output:**

```text
[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]
```


In [25]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')    #delimiter: The string used to separate values
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


## 26. Extract a Particular Column From a 1D Structured Array

**Question:** Extract the text column species (5th field) from the 1D structured array iris\_1d.

**Expected Output:**

```text
(150,)
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']
```


In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

species = np.array([row[4] for row in iris_1d])
print(species[:5])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


## 27. Convert a 1D Structured Array to a 2D Numeric Array

**Question:** Convert the 1D structured array iris\_1d to a 2D array iris\_2d by omitting the species text field and keeping only the four numeric columns.

**Expected Output:**

```text
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]]
```


In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


## 28. Compute Mean, Median, and Standard Deviation

**Question:** **Question:** Find the mean, median, and standard deviation of the sepallength column (1st column) from the iris dataset.

**Expected Output:**

```text
5.84333333333 5.8 0.825301291785
```


In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


## 29. Normalize an Array to the 0-1 Range

**Question:** Normalize the sepallength array so the minimum maps to 0 and the maximum maps to 1.

**Expected Output:**

```text
[ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
  0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
  0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
  0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
  0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
  0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
  0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
  0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
  0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
  0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
  0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
  0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
  0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
  0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
  0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]
```


In [29]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin) / (Smax - Smin)
print(S)


[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

## 30. Compute the Softmax Score

**Question:** Compute the softmax scores for the sepallength array.

**Expected Output:**

```text
[ 0.002  0.002  0.001  0.001  0.002  0.003  0.001  0.002  0.001  0.002
  0.003  0.002  0.002  0.001  0.004  0.004  0.003  0.002  0.004  0.002
  0.003  0.002  0.001  0.002  0.002  0.002  0.002  0.002  0.002  0.001
  0.002  0.003  0.002  0.003  0.002  0.002  0.003  0.002  0.001  0.002
  0.002  0.001  0.001  0.002  0.002  0.002  0.002  0.001  0.003  0.002
  0.015  0.008  0.013  0.003  0.009  0.004  0.007  0.002  0.01   0.002
  0.002  0.005  0.005  0.006  0.004  0.011  0.004  0.004  0.007  0.004
  0.005  0.006  0.007  0.006  0.008  0.01   0.012  0.011  0.005  0.004
  0.003  0.003  0.004  0.005  0.003  0.005  0.011  0.007  0.004  0.003
  0.003  0.006  0.004  0.002  0.004  0.004  0.004  0.007  0.002  0.004
  0.007  0.004  0.016  0.007  0.009  0.027  0.002  0.02   0.011  0.018
  0.009  0.008  0.012  0.004  0.004  0.008  0.009  0.03   0.03   0.005
  0.013  0.004  0.03   0.007  0.011  0.018  0.007  0.006  0.008  0.018
  0.022  0.037  0.008  0.007  0.006  0.03   0.007  0.008  0.005  0.013
  0.011  0.013  0.004  0.012  0.011  0.011  0.007  0.009  0.007  0.005]
```


In [30]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))


[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

## 31. Find Percentile Scores

**Question:** Find the 5th and 95th percentile of the sepallength array.

**Expected Output:**

```text
[ 4.6    7.255]
```


In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

result = np.percentile(sepallength, q=[5, 95])
print(result)

[4.6   7.255]


## 32. Insert Values at Random Positions

**Question:** Insert np.nan at 20 random positions in the iris\_2d dataset.

**Expected Output:**

```text
[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]
 ```


In [32]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print(iris_2d[:10])


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


## 33. Find the Position of Missing Values

**Question:** Find the number and position of missing values in iris\_2d‘s sepallength (1st column).

**Expected Output:**

```text
Number of missing values:
 5
Position of missing values:
 (array([ 39,  88,  99, 130, 147]),)
```


In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 4
Position of missing values: 
 (array([14, 34, 79, 87]),)


## 34. Filter a NumPy Array Based on Multiple Conditions

**Question:** Filter the rows of iris\_2d where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0.

**Expected Output:**

```text
[[ 4.8  3.4  1.6  0.2]
 [ 4.8  3.4  1.9  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 4.9  2.4  3.3  1. ]
 [ 4.9  2.5  4.5  1.7]]
```


In [34]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

result = iris_2d[(iris_2d[:,2]>1.5)&(iris_2d[:,0]<5.0)]
print(result)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## 35. Drop Rows Containing Missing Values

**Question:** Select the rows of iris\_2d that do not have any nan value, keeping only complete rows.

**Expected Output:**

```text
array([[ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4]])
```


In [35]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

result = iris_2d[np.sum(np.isnan(iris_2d), axis=1) == 0][:5]
print(result)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]


## 36. Find Correlation Between Two Columns

**Question:** Compute the Pearson correlation between SepalLength (1st column) and PetalLength (3rd column) in iris\_2d.

**Expected Output:**

```text
0.871754157305
```


In [36]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

print(np.corrcoef(iris[:, 0], iris[:, 2])[0, 1])

0.8717541573048718


## 37. Check for Missing Values in an Array

**Question:** Determine whether iris\_2d has any missing (nan) values and print the boolean result.

**Expected Output:**

```text
False
```


In [37]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

print(np.isnan(iris_2d).any())

False


## 38. Replace All Missing Values with Zero

**Question:** Replace all nan values in iris\_2d with 0 and print the first four rows.

**Expected Output:**

```text
array([[ 5.1,  3.5,  1.4,  0. ],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2]])
```


In [38]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0
print(iris_2d[:4])

[[0.  3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


## 39. Count Unique Values in an Array

**Question:** Find the unique values and their counts in the species column of the iris dataset.

**Expected Output:**

```text
(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50]))
```


In [39]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = np.array([row.tolist()[4] for row in iris])
print(np.unique(species, return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype='|S15'), array([50, 50, 50]))


## 40. Bin a Numeric Column into Categories

**Question:** Bin the petal length (3rd column) of iris into a text array using these rules: less than 3 becomes 'small', 3 to 5 becomes 'medium', and 5 or above becomes 'large'.

**Expected Output:**

```text
['small', 'small', 'small', 'small']
```


In [40]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10]) #This function returns the indices of the bins to which each value in an input array belongs.

label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
print(petal_length_cat[:4])


['small', 'small', 'small', 'small']


## 41. Create a New Column from Existing Columns

**Question:** Add a new column to iris\_2d for volume, computed as (pi x petallength x sepallength^2) / 3.

**Expected Output:**

```text
array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa', 38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa', 35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa', 33.238050274980004]], dtype=object)
```


In [41]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2)) / 3

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]
out = np.hstack([iris_2d, volume])

print(out[:4])


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 38.13265162927291]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 35.200498485922445]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 30.0723720777127]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 33.238050274980004]]


## 42. Probabilistic Sampling from a Categorical Array

**Question:** Randomly sample from iris‘s species column such that setosa appears twice as often as versicolor and virginica.

**Expected Output:**

```text
(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'], dtype=object), array([77, 37, 36]))
```
Why this matters: Probabilistic sampling is used in class balancing, bootstrapping, and data augmentation for imbalanced datasets.

In [42]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

species = iris[:, 4]

np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
print(np.unique(species_out, return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([77, 37, 36]))


## 43. Get the Second Largest Value by Group

**Question:** Find the second longest petallength among species setosa in the iris dataset.

**Expected Output:**

```text
1.7
```
Why this matters: Computing grouped statistics beyond simple max/min is common in exploratory data analysis and outlier detection.

In [43]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

print(np.unique(np.sort(petal_len_setosa))[-2])

1.7


## 44. Sort a 2D Array by a Column

**Question:** Sort the iris dataset based on the sepallength column (1st column) in ascending order.

**Expected Output:**

```text
[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]
```
Why this matters: Sorting datasets by a specific feature is fundamental for ranking, binary search, and ordered visualizations.

In [44]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


## 45. Find the Most Frequent Value in an Array

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

**Expected Output:**

```text
b'1.5'
```
Why this matters: Identifying the mode of a feature helps detect dominant patterns and is used in imputation strategies.

In [45]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


## 46. Find the First Occurrence Greater Than a Value

**Question:** Find the position of the first occurrence of a value greater than 1.0 in the petalwidth (4th column) of the iris dataset.

**Expected Output:**

```text
50
```
Why this matters: Locating threshold crossings is used in signal processing, event detection, and conditional filtering of datasets.



In [46]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

print(np.argwhere(iris[:, 3].astype(float) > 1.0)[0])

[50]


## 47. Clip Array Values to a Range

**Question:** From the array a, replace all values greater than 30 with 30 and all values less than 10 with 10.

**Expected Output:**

```text
[ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
  11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]
```
Why this matters: Clipping values to a valid range is essential for outlier handling and ensuring inputs stay within expected bounds for models.

In [47]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

a[np.where(a<10)]=10
a[np.where(a>30)]=30
np.set_printoptions(precision=2)
print(a)

[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


## 48. Get the Positions of Top N Values

**Question:** Get the positions of the top 5 maximum values in the array a.

**Expected Output:**

```text
[18 7 3 10 15]
```
Why this matters: Finding top-N indices is used in ranking systems, recommendation engines, and selecting the highest-confidence predictions.

In [48]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

print(a.argsort()[-5:])

[18  7  3 10 15]


## 49. Compute Row-Wise Counts of All Possible Values

**Question:** For each row in arr, count the occurrences of every value from 1 to 10.

**Expected Output:**

```text
[ 1  2  3  4  5  6  7  8  9 10]
[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```
Why this matters: Row-wise value counting is used in bag-of-words representations and histogram-based feature extraction.

In [49]:
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))
print(arr)

def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # This nested list comprehension normalizes the counts so every row's output has the same length, mapping perfectly to the global unique values (1 through 10)
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

print(np.arange(1, 11))
result = counts_of_all_values_rowwise(arr)
for row in result:
    print(row)

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[1, 0, 2, 1, 1, 1, 0, 2, 2, 0]
[2, 1, 3, 0, 1, 0, 1, 0, 1, 1]
[0, 3, 0, 2, 3, 1, 0, 1, 0, 0]
[1, 0, 2, 1, 0, 1, 0, 2, 1, 2]
[2, 2, 2, 0, 0, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 2, 0, 0, 2, 1]


/tmp/ipykernel_2571/2886867561.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])


## 50. Flatten an Array of Arrays into a 1D Array

**Question:** Convert array\_of\_arrays (which contains arr1, arr2, and arr3) into a single flat 1D array.

**Expected Output:**

```text
[0 1 2 3 4 5 6 7 8 9]
```
Why this matters: Flattening nested array structures is a routine step when combining data from multiple sources into a single feature vector.

In [50]:
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

array_of_arrays = np.array([arr1, arr2, arr3], dtype=object)
print(array_of_arrays)

arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


## 51. Generate One-Hot Encodings for an Array

**Question:** Compute one-hot encodings (dummy binary variables) for each unique value in arr.

**Expected Output:**

```text
array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])
```
Why this matters: One-hot encoding converts categorical integers into binary vectors, which is required by most ML algorithms that expect numeric input.

In [51]:
np.random.seed(101)
arr = np.random.randint(1, 4, size=6)
print(arr)

# Method 1:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)    #Finds the distinct values in the array (e.g., [1, 2, 3])
    out = np.zeros((arr.shape[0], uniqs.shape[0]))    #Creates a matrix filled with zeros. The number of rows matches the length of the input array (6), and the number of columns matches the number of unique values (3).
    for i, k in enumerate(arr):
        out[i, k-1] = 1   #Places a 1 in the correct column. Because Python is 0-indexed and the random values start at 1, k-1 shifts the value to act as a valid column index (value 1 goes to column 0, value 2 goes to column 1).
    return out
# Note: This specific function is slightly fragile—if the random array happens to missing the number 1, k-1 will place values in the wrong columns or throw an index error.
print(one_hot_encodings(arr))

# Method 2:
# arr[:, None]       -> Reshapes the 1D array into a 2D column vector
# == np.unique(arr)  -> Broadcasts the comparison, creating a grid of True/False matches
# .view(np.int8)     -> Converts the True/False boolean grid into 1s and 0s
print((arr[:, None] == np.unique(arr)).view(np.int8))

[2 3 2 2 2 1]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


## 52. Create Row Numbers Grouped by a Categorical Variable

**Question:** Assign within-group row numbers to each element in species\_small, restarting the count at 0 for each new species.

**Expected Output:**

```text
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]
```
Why this matters: Grouped row numbering is useful for creating sequence features and ranking within categories in data analysis.

In [53]:
#The code fetches the Iris dataset, randomly selects and alphabetically sorts 20 species, and then generates a zero-based running count for how many times each species has appeared in the sorted list.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))

#Method 1:
# print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

#Method 2:
_, counts = np.unique(species_small, return_counts=True)
result = np.concatenate([np.arange(c) for c in counts])
print(result)

[0 1 2 3 4 0 1 2 3 4 5 6 7 8 0 1 2 3 4 5]


## 53. Create Group IDs from a Categorical Variable

**Question:** Assign a numeric group ID (0, 1, 2, …) to each element in species\_small based on its unique species category.

**Expected Output:**

```text
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]
```
Why this matters: Converting categorical labels to integer group IDs is a standard preprocessing step for label encoding in ML pipelines.


In [55]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))


output = []
uniqs = np.unique(species_small)

for val in uniqs:  # Looks at one unique flower type at a time.
    for s in species_small[species_small==val]:  # Loops through every actual flower in your 20-item list that matches the current type.
        groupid = np.argwhere(uniqs == s).tolist()[0][0]  # : Searches the uniqs list to find the index position of the current flower.
        output.append(groupid)

print(output)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


## 54. Rank Items in a 1D Array

**Question:** Create the ranks for each value in the numeric array a, where rank 0 is the smallest value.

**Expected Output:**

```text
[4 2 6 0 8 7 9 3 5 1]





```


## 55. Rank Items in a Multidimensional Array

**Question:** Create a rank array of the same shape as the 2D array a, where ranking is applied globally across all elements.

**Expected Output:**

```text
[[4 2 6 0 8]
 [7 9 3 5 1]]





```


## 56. Find the Maximum Value in Each Row

**Question:** Compute the maximum value for each row in the 2D array a.

**Expected Output:**

```text
array([9, 8, 6, 3, 9])





```


## 57. Compute the Min-by-Max Ratio for Each Row

**Question:** Compute the ratio of the minimum to the maximum value for each row in the 2D array a.

**Expected Output:**

```text
array([ 0.44444444,  0.125     ,  0.5       ,  1.        ,  0.11111111])





```


## 58. Find Duplicate Records in an Array

**Question:** Mark duplicate entries in array a as True (2nd occurrence onwards), with first occurrences marked as False.

**Expected Output:**

```text
[False  True False  True False False  True  True  True  True]





```


## 59. Find the Grouped Mean

**Question:** Compute the mean of sepalwidth (2nd column) grouped by species (5th column) in the iris dataset.

**Expected Output:**

```text
[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.770],
 [b'Iris-virginica', 2.974]]





```


## 60. Convert a PIL Image to a NumPy Array

**Question:** Import the image from the given URL and convert it to a numpy array, printing its shape.

**Expected Output:**

```text
A numpy array representation of the image with shape (height, width, 3)





```


## 61. Drop All Missing Values from a 1D Array

**Question:** Remove all nan values from the 1D array a and return only the valid elements.

**Expected Output:**

```text
array([ 1.,  2.,  3.,  5.,  6.,  7.])





```


## 62. Compute the Euclidean Distance Between Two Arrays

**Question:** Compute the Euclidean distance between arrays a and b.

**Expected Output:**

```text
6.7082039324993694





```


## 63. Find All Local Maxima (Peaks) in a 1D Array

**Question:** Find the positions of all peaks in array a, where peaks are values surrounded by smaller values on both sides.

**Expected Output:**

```text
array([2, 5])





```


## 64. Subtract a 1D Array from a 2D Array Row-Wise

**Question:** Subtract each element of b\_1d from the corresponding row of a\_2d, so that b\_1d[0] is subtracted from all elements in row 0, b\_1d[1] from row 1, and so on.

**Expected Output:**

```text
[[2 2 2]
 [2 2 2]
 [2 2 2]]





```


## 65. Find the Index of the N’th Repetition of a Value

**Question:** Find the index of the 5th repetition of the value 1 in array x.

**Expected Output:**

```text
8





```


## 66. Convert NumPy datetime64 to Python datetime

**Question:** Convert the numpy datetime64 object dt64 to a Python datetime.datetime object.

**Expected Output:**

```text
datetime.datetime(2018, 2, 25, 22, 10, 10)





```


## 67. Compute the Moving Average of an Array

**Question:** Compute the moving average of array Z with a window size of 3.

**Expected Output:**

```text
array:  [8 8 3 7 7 0 4 2 5 2]
moving average:  [ 6.33  6.    5.67  4.67  3.67  2.    3.67  3.  ]





```


## 68. Create an Array Sequence Given Start, Length, and Step

**Question:** Create a numpy array of length 10, starting from 5, with a step of 3 between consecutive numbers using the variables start, length, and step.

**Expected Output:**

```text
array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])





```


## 69. Fill in Missing Dates in an Irregular Date Series

**Question:** Given the array dates containing every other day, fill in the missing dates to create a continuous daily sequence.

**Expected Output:**

```text
['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04'
 '2018-02-05' '2018-02-06' '2018-02-07' '2018-02-08'
 '2018-02-09' '2018-02-10' '2018-02-11' '2018-02-12'
 '2018-02-13' '2018-02-14' '2018-02-15' '2018-02-16'
 '2018-02-17' '2018-02-18' '2018-02-19' '2018-02-20'
 '2018-02-21' '2018-02-22' '2018-02-23']





```


## 70. Create Strides from a 1D Array

**Question:** From the array arr, generate a 2D matrix using strides with a window length of 4 and stride of 2, producing rows like [0,1,2,3], [2,3,4,5], [4,5,6,7]....

**Expected Output:**

```text
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]





```


## 71. How to create an array using a function of its row and column indices?

**Question:** Create a 4×5 array where each element equals the sum of its row and column index using np.fromfunction.

**Expected Output:**

```text
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]





```


## 72. How does array broadcasting work?

**Question:** Add the column vector a (shape 3×1) and row vector b (shape 3,) using broadcasting to produce a 3×3 result.

**Expected Output:**

```text
[[11 21 31]
 [12 22 32]
 [13 23 33]]





```


## 73. How to create coordinate grids with np.meshgrid?

**Question:** Create coordinate matrices X and Y from arrays x and y using np.meshgrid, and print both.

**Expected Output:**

```text
X:
[[1 2 3]
 [1 2 3]]
Y:
[[4 4 4]
 [5 5 5]]





```


## 74. How to standardize columns of a 2D array (zero mean, unit variance)?

**Question:** Standardize each column of the random array a so that each column has mean 0 and standard deviation 1, then verify by printing the resulting means and stds.

**Expected Output:**

```text
Means after standardization: [-0.  0.  0.]
Stds after standardization: [1. 1. 1.]





```


## 75. How to create and use structured arrays?

**Question:** Create a structured array with fields name (string), age (int), and weight (float) containing three records, then extract and print the name field.

**Expected Output:**

```text
[('Alice', 25, 55.5) ('Bob', 30, 75. ) ('Charlie', 35, 65.2)]
Names: ['Alice' 'Bob' 'Charlie']





```


## 76. How to use fancy indexing to select specific elements?

**Question:** Select elements at positions (0,1), (1,3), and (3,4) from the 4×5 array a using fancy indexing with row and column index arrays.

**Expected Output:**

```text
[ 1  8 19]





```


## 77. How to compute cumulative sum and cumulative product?

**Question:** Compute and print the cumulative sum and cumulative product of the array a = [1, 2, 3, 4, 5] using np.cumsum and np.cumprod.

**Expected Output:**

```text
Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]





```


## 78. How to compute cumulative sum along a specific axis of a 2D array?

**Question:** Compute the cumulative sum of the 2D array a along axis=0 (down columns) and axis=1 (across rows), and print both results.

**Expected Output:**

```text
Cumsum along rows (axis=0):
[[ 7  4  8  5]
 [14  7 15 13]
 [19 11 23 21]]
Cumsum along columns (axis=1):
[[ 7 11 19 24]
 [ 7 10 17 25]
 [ 5  9 17 25]]





```


## 79. How to compute a dot product using np.einsum?

**Question:** Compute the dot product of arrays a = [1, 2, 3] and b = [4, 5, 6] using np.einsum with the subscript string 'i,i->'.

**Expected Output:**

```text
32





```


## 80. How to multiply two matrices using np.einsum?

**Question:** Multiply matrices A and B using np.einsum with the subscript string 'ij,jk->ik' and print the result.

**Expected Output:**

```text
[[19 22]
 [43 50]]





```


## 81. How to apply a custom function to every row or column of an array?

**Question:** Compute the range (max minus min) of each row in array a using np.apply\_along\_axis with axis=1.

**Expected Output:**

```text
Range per row: [16  9 13 14]





```


## 82. How to get the rank of each element in an array?

**Question:** Get the rank (sorted position) of each element in array a using the double argsort trick: a.argsort().argsort().

**Expected Output:**

```text
Ranks: [4 2 6 0 8 7 9 3 5 1]





```


## 83. How to compute matrix determinant and inverse?

**Question:** Compute and print the determinant and inverse of matrix A = [[1, 2], [3, 4]] using np.linalg.det and np.linalg.inv.

**Expected Output:**

```text
Determinant: -2.0
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]





```


## 84. How to solve a system of linear equations with NumPy?

**Question:** Solve the system 3x + y = 9, x + 2y = 8 by passing the coefficient matrix A and constants vector b to np.linalg.solve.

**Expected Output:**

```text
Solution [x, y]: [2. 3.]





```


## 85. How to compute eigenvalues and eigenvectors?

**Question:** Compute and print the eigenvalues and eigenvectors of matrix A = [[4, -2], [1, 1]] using np.linalg.eig.

**Expected Output:**

```text
Eigenvalues: [3. 2.]
Eigenvectors:
[[ 0.89442719  0.70710678]
 [ 0.4472136   0.70710678]]





```


## 86. How to fit a polynomial curve to noisy data?

**Question:** Fit a degree-2 polynomial to the noisy data arrays x and y using np.polyfit, then evaluate it with np.polyval and print the fitted coefficients and first 5 predicted values.

**Expected Output:**

```text
Fitted coefficients [a, b, c]: [ 1.98 -2.89  1.15]
First 5 predicted values: [1.15 0.16 0.38 1.83 4.49]





```


## 87. How to select rows with a boolean mask and specific columns at the same time?

**Question:** Select rows from array a where mask is True, and take only the first 3 columns, using combined boolean and slice indexing: a[mask, :3].

**Expected Output:**

```text
[[ 0  1  2]
 [10 11 12]]





```


## 88. How to compute the outer product of two vectors?

**Question:** Compute the outer product of arrays a = [1, 2, 3] and b = [4, 5, 6] using np.multiply.outer and print the resulting 3×3 matrix.

**Expected Output:**

```text
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]





```


## 89. How to compute a rolling/moving average of a 1D array?

**Question:** Compute a 3-element moving average of array a using np.convolve with a uniform kernel of size 3 and mode='valid'.

**Expected Output:**

```text
Moving average (window=3): [ 7.67  5.33  7.33  8.67  8.33 10.67 13.   12.  ]





```


## 90. How to rotate a 2D array (like an image)?

**Question:** Rotate the 3×4 array img by 90 degrees counter-clockwise using np.rot90 and print the result.

**Expected Output:**

```text
Rotated 90 degrees:
[[ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]
 [ 0  4  8]]





```


## 91. How to flip an array horizontally and vertically?

**Question:** Flip the 3×4 array img left-to-right using np.fliplr and top-to-bottom using np.flipud, printing both results.

**Expected Output:**

```text
Flipped left-right:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
Flipped up-down:
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]





```


## 92. How to pad an array with zeros on all sides?

**Question:** Pad the 3×3 array of ones a with one layer of zeros on all sides using np.pad with mode='constant'.

**Expected Output:**

```text
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]





```


## 93. How to create sliding windows over an array?

**Question:** Create sliding windows of size 4 over the array a = np.arange(10) using sliding\_window\_view and print the resulting 2D array of windows.

**Expected Output:**

```text
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]





```


## 94. How to compute min-max normalization to scale values between 0 and 1?

**Question:** Min-max normalize each column of the 2D array a to the range [0, 1] by subtracting the column min and dividing by the column range, then verify the min and max of each column.

**Expected Output:**

```text
Min after normalization: [0. 0. 0.]
Max after normalization: [1. 1. 1.]





```


## 95. How to compute a weighted average?

**Question:** Compute the weighted average of scores using weights with np.average, and compare it against the simple mean from np.mean.

**Expected Output:**

```text
Weighted average: 85.9
Simple average: 86.6





```


## 96. How to find the top-k similar items using cosine similarity?

**Question:** Compute the cosine similarity between the query vector and each row in items using dot products and norms, then find the index of the most similar item with np.argmax.

**Expected Output:**

```text
Cosine similarities: [0.896 0.928 0.811 0.852 0.866]
Most similar item index: 1





```


## 97. How to compute the covariance matrix of a dataset?

**Question:** Compute the covariance matrix of the 3-feature data array using np.cov(data.T), then print the covariance between feature 0 and feature 1 (positive) and between feature 0 and feature 2 (negative).

**Expected Output:**

```text
Covariance matrix shape: (3, 3)
Feature 0-1 covariance (should be positive): 1.88
Feature 0-2 covariance (should be negative): -0.96





```


## 98. How to perform one-step PCA using eigendecomposition?

**Question:** Reduce the 4-feature data array to 2 principal components by centering the data, computing the covariance matrix, performing eigendecomposition with np.linalg.eig, selecting the top-2 eigenvectors, and projecting the data.

**Expected Output:**

```text
Original shape: (50, 4)
Projected shape: (50, 2)
Variance explained by top 2 components: 89.2%





```


## 99. How to compute 2D sliding windows over a matrix?

**Question:** Create 3×3 sliding windows over the 5×5 array a using sliding\_window\_view(a, (3, 3)), then print the shape of the result and the first window (top-left corner).

**Expected Output:**

```text
Windows shape: (3, 3, 3, 3)
First window (top-left):
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]





```


## 100. How to do batch matrix multiplication with np.einsum?

**Question:** Multiply each pair of matrices in batches A (shape 3x2x3) and B (shape 3x3x2) using np.einsum('bij,bjk->bik', A, B) so that result[i] = A[i] @ B[i].

**Expected Output:**

```text
Result shape: (3, 2, 2)
Result:
[[[22 17]
  [26 28]]

 [[18 16]
  [26 22]]

 [[23 13]
  [25 13]]]





```


## 101. How to compute a pairwise Euclidean distance matrix without loops?

**Question:** Compute the 5×5 pairwise Euclidean distance matrix for the points array (5 points in 3D) using broadcasting and np.einsum, without any Python loops.

**Expected Output:**

```text





```
